---
galaxy_info:
  author: Adam Hassick
  description: Deploys the OpenHorizon Management Hub
  company: UNH InterOperability Lab
  license: "Apache-2.0"
  min_ansible_version: "2.1"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags: []
dependencies: []
