---
# Generates an agent-install.cfg file for operations.

- name: Ensure pip is installed
  ansible.builtin.apt:
    state: present
    name: python3-pip
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: Install dependencies
  ansible.builtin.pip:
    state: present
    name: python-dotenv

- name: Copy script from local
  ansible.builtin.copy:
    src: deploy-mgmt-hub.sh
    dest: deploy-mgmt-hub.sh

# Copy the environment file to the remote system (if it exists).
- name: Copy environment to destination
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    src: '{{ agent_install }}'
    dest: '{{ agent_install }}'
  when: agent_install is defined and agent_install != None

# Generate an agent-install.cfg file from environment and YAML variables.
- name: Generate environment for install
  load_env_config:
    ansible_facts: "{{ ansible_facts }}"
    mgmt_hub: '{{ hzn_mgmt_hub }}'
    env_file: '{{ agent_install }}'
  register: install_config

# Write the agent-install.cfg file to disk.
- name: Write finalized environment file to disk.
  ansible.builtin.copy:
    mode: '0644'
    content: "{{ install_config.env_script }}"
    dest: agent-install.cfg
