---
# tasks file for hzn-mgmt-hub

- name: Install dependencies
  ansible.builtin.pip:
    state: "present"
    name: python-dotenv

# Copy the environment file to the remote system (if it exists).
- name: Copy environment to destination
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    src: '{{ agent_install }}'
    dest: '{{ agent_install }}'
  when: agent_install is defined and agent_install != None

# - name: Copy management hub script to destination
#   ansible.builtin.copy:
#     src: deploy-mgmt-hub.sh
#     dest: deploy-mgmt-hub.sh

# Generate an agent-install.cfg file from environment and YAML variables.
- name: Generate environment for install
  load_env_config:
    ansible_facts: "{{ ansible_facts }}"
    mgmt_hub: '{{ hzn_mgmt_hub }}'
    env_file: '{{ agent_install }}'
  register: install_config

# Write the agent-install.cfg file to disk.
- name: Write finalized environment file to disk.
  ansible.builtin.copy:
    mode: '0644'
    content: "{{ install_config.env_script }}"
    dest: agent-install.cfg

  # The next two steps are mutually exclusive.

  # Installs the management hub (if fails, shuts down the hub)
- name: Begin installation of the management hub
  block:
    # Note: This is meant to be temporary.
    #   The next step here is to introduce this playbook as a separate
    #     product from the shell installer.
    #   A good Ansible role never executes shell scripts like
    #     this, and will always rely on tasks and modules instead.
    #   This role should be extended to perform the same steps
    #     that the deploy-mgmt-hub script performs.
  - name: Execute installer script
    ansible.builtin.script: deploy-mgmt-hub.sh -c agent-install.cfg
  # If the installation fails above, shut down the containers.
  rescue:
  - name: Stop containers
    ansible.builtin.script: deploy-mgmt-hub.sh -c agent-install.cfg -S
  - name: Display warning message
    ansible.builtin.debug:
      msg: "Failed to install or start the management hub containers."
  - name: Force failure
    ansible.builtin.shell: "exit 1"
  when: not uninstall

  # Uninstalls the management hub
- name: Begin uninstallation of the management hub
  ansible.builtin.script: deploy-mgmt-hub.sh -c agent-install.cfg -S -P
  when: uninstall

  # Optionally export variables
- name: Export variables
  ansible.builtin.file:
    content: '{{ install_config.hzn_mgmt_hub }}'
    dest: mgmt_hub_configuration.yml
  when: export_data

- name: Run user and group management
  import_tasks: user_mgmt.yml
  when: not uninstall